/*
  # Create Feedback Requests Table and Policies

  1. New Tables
    - `feedback_requests`
      - `id` (bigint, primary key, auto-generated)
      - `ticket_id` (bigint, nullable)
      - `created_at` (timestamptz, default now())
      - `platform` (text)
      - `product` (text)
      - `description` (text)
      - `core_team_acknowledgement` (boolean)
      - `shipped` (boolean)
      - `shipping_date` (date)

  2. Security
    - Enable RLS on `feedback_requests` table
    - Add policies for anonymous and authenticated users for all CRUD operations
*/

-- Create the feedback_requests table if it doesn't exist
CREATE TABLE IF NOT EXISTS feedback_requests (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticket_id bigint,
  created_at timestamptz DEFAULT now(),
  platform text,
  product text,
  description text,
  core_team_acknowledgement boolean,
  shipped boolean,
  shipping_date date
);

-- Enable RLS
ALTER TABLE feedback_requests ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist to avoid conflicts
DROP POLICY IF EXISTS "Allow anonymous insert access" ON feedback_requests;
DROP POLICY IF EXISTS "Allow anonymous read access" ON feedback_requests;
DROP POLICY IF EXISTS "Allow anonymous update access" ON feedback_requests;
DROP POLICY IF EXISTS "Allow anonymous delete access" ON feedback_requests;
DROP POLICY IF EXISTS "Allow authenticated insert access" ON feedback_requests;
DROP POLICY IF EXISTS "Allow authenticated read access" ON feedback_requests;
DROP POLICY IF EXISTS "Allow authenticated update access" ON feedback_requests;
DROP POLICY IF EXISTS "Allow authenticated delete access" ON feedback_requests;

-- Add RLS policies for anonymous users
CREATE POLICY "Allow anonymous insert access"
  ON feedback_requests
  FOR INSERT
  TO anon
  WITH CHECK (true);

CREATE POLICY "Allow anonymous read access"
  ON feedback_requests
  FOR SELECT
  TO anon
  USING (true);

CREATE POLICY "Allow anonymous update access"
  ON feedback_requests
  FOR UPDATE
  TO anon
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow anonymous delete access"
  ON feedback_requests
  FOR DELETE
  TO anon
  USING (true);

-- Add RLS policies for authenticated users
CREATE POLICY "Allow authenticated insert access"
  ON feedback_requests
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated read access"
  ON feedback_requests
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated update access"
  ON feedback_requests
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow authenticated delete access"
  ON feedback_requests
  FOR DELETE
  TO authenticated
  USING (true);